name = "web-desa-citarik"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

workers_dev = true
routes = [{ pattern = "desacitarik.web.id/*", zone_name = "desacitarik.web.id" }]

[[d1_databases]]
binding = "DB"
database_name = "web-desa-citarik-db"
database_id = "99cfd971-5422-46f9-b9a9-4a57eb32adb3"

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "web-desa-citarik-media"

[[kv_namespaces]]
binding = "SESSION_KV"
id = "d600a6633c8043238a1c57097b2d2b24"

[triggers]
crons = []

[dev]
port = 4321
