-- ─────────────────────────────────────────────────────────────
-- Story: SEO + konten upgrade (grafik profil, teks wisata lebih lengkap,
-- berita peluncuran situs, dan pembersihan tanda pisah panjang/em dash).
-- Aman dijalankan berulang (idempotent).
-- ─────────────────────────────────────────────────────────────

-- ── Profil umum: data Prodeskel Maret 2025 (final override di 0006) ──
INSERT INTO page_section (slug, title, content_html) VALUES
  ('profil-umum', 'Profil Umum',
   '<p>Desa Citarik terletak di Kecamatan Palabuhanratu, Kabupaten Sukabumi, Provinsi Jawa Barat (kode desa 3202110005). Berdasarkan isian Prodeskel Maret 2025, desa ini memiliki 4 dusun, 10 RW, dan 50 RT, dengan jumlah penduduk 13.187 jiwa (6.750 laki-laki, 6.437 perempuan) dari 4.220 kepala keluarga.</p><p>Jarak ke ibu kota kecamatan maupun ibu kota kabupaten masing-masing sekitar 6 km (±0,15 jam dengan kendaraan bermotor). Jarak ke ibu kota provinsi sekitar 150 km (±6 jam bermotor).</p><ul><li><strong>Kecamatan:</strong> Palabuhanratu</li><li><strong>Kabupaten:</strong> Sukabumi</li><li><strong>Provinsi:</strong> Jawa Barat</li><li><strong>Kode desa:</strong> 3202110005</li><li><strong>Sumber data:</strong> Profil Desa dan Kelurahan (Prodeskel), Maret 2025</li></ul>')
ON CONFLICT(slug) DO UPDATE SET title=excluded.title, content_html=excluded.content_html, updated_at=datetime('now');

-- ── Wisata: deskripsi lebih lengkap untuk tiap destinasi (daya tarik, akses, tips) ──
INSERT INTO wisata (slug, nama, deskripsi_html, status) VALUES
  ('pantai-Citarik', 'Pantai Citarik',
   '<p>Pantai Citarik membentang sepanjang kurang lebih 4 km di tepi Samudra Hindia, menjadikannya salah satu garis pantai terpanjang di Kecamatan Simpenan. Ombaknya yang cukup besar khas pantai selatan Jawa cocok dinikmati dari tepian sambil melihat aktivitas nelayan setempat yang masih menggunakan cara tangkap tradisional.</p><h2>Daya Tarik</h2><p>Selain hamparan pasir dan deburan ombak, kawasan ini menjadi bagian dari Geopark Ciletuh-Palabuhanratu sehingga sering disinggahi wisatawan yang sedang menjelajahi jalur geopark. Desa Citarik sendiri pernah meraih Juara I Program Desa Pesisir Tangguh (PDPT) tingkat Kabupaten, salah satunya berkat pengelolaan kawasan pesisir ini.</p><h2>Akses</h2><p>Pantai Citarik dapat dijangkau dari pusat Kecamatan Simpenan dalam waktu sekitar 10-15 menit berkendara. Jalan menuju pantai sudah beraspal meski disarankan menggunakan kendaraan yang nyaman untuk medan berbukit di beberapa titik.</p><h2>Tips Berkunjung</h2><p>Datanglah pada pagi atau sore hari untuk menghindari terik matahari, dan tetap berhati-hati saat berenang karena arus laut selatan cukup kuat.</p>', 'published'),

  ('danau-talanca', 'Danau Talanca',
   '<p>Danau Talanca adalah badan air seluas sekitar 20 hektar yang terletak di kawasan Desa Citarik. Airnya yang tenang menjadikan danau ini kontras dengan ombak Pantai Citarik yang hanya berjarak beberapa kilometer.</p><h2>Potensi</h2><p>Warga setempat memanfaatkan danau ini untuk kegiatan perikanan air tawar, dan pemerintah desa melihat peluang besar untuk mengembangkannya menjadi kawasan wisata air seperti memancing, berperahu, atau susur danau bagi wisatawan yang ingin suasana lebih tenang.</p><h2>Akses</h2><p>Danau Talanca berada tidak jauh dari pemukiman warga sehingga cukup mudah dijangkau menggunakan kendaraan roda dua maupun roda empat. Warga sekitar biasanya dapat membantu menunjukkan jalan bagi pengunjung baru.</p>', 'published'),

  ('muara-Citarik-sidat', 'Muara Citarik (Kampung Sidat)',
   '<p>Muara Citarik dikenal sebagai kawasan budidaya sidat, sejenis belut air tawar bernilai ekonomi tinggi yang banyak dicari untuk pasar ekspor. Kawasan muara ini menjadi pertemuan antara aliran sungai dan laut, kondisi alami yang mendukung siklus hidup sidat.</p><h2>Potensi Wisata dan Edukasi</h2><p>Selain sebagai sentra budidaya, Muara Citarik berpotensi dikembangkan menjadi destinasi wisata edukasi, tempat pengunjung bisa belajar langsung tentang cara budidaya sidat dari warga setempat sekaligus menikmati suasana muara yang asri.</p><h2>Akses</h2><p>Lokasi ini berada di kawasan pesisir Desa Citarik, dapat ditempuh dengan kendaraan pribadi dari pusat desa.</p>', 'published'),

  ('air-panas-sawah-beura', 'Pemandian Air Panas Sawah Beura',
   '<p>Di Kampung Sawah Beura terdapat sumber air panas alami yang keluar langsung dari dalam tanah. Fenomena ini cukup jarang ditemui di kawasan pesisir dan menjadi salah satu kekayaan alam yang dimiliki Desa Citarik.</p><h2>Potensi</h2><p>Air panas alami dipercaya sebagian warga memiliki manfaat untuk relaksasi dan kesehatan kulit. Dengan penataan yang lebih baik, kawasan ini berpotensi menjadi destinasi wisata pemandian air panas yang melengkapi wisata bahari di Desa Citarik.</p><h2>Akses</h2><p>Sumber air panas ini berada di Kampung Sawah Beura, dapat dicapai dengan berkendara dari pusat desa lalu dilanjutkan dengan berjalan kaki melewati jalan kampung.</p>', 'published'),

  ('puncak-gelendrung', 'Puncak Gelendrung',
   '<p>Puncak Gelendrung berada di kawasan Gunung Rompang dan menawarkan panorama alam Desa Citarik dari ketinggian, mulai dari hamparan sawah, perbukitan, hingga garis pantai yang membentang di kejauhan.</p><h2>Daya Tarik</h2><p>Kontur perbukitan dan hembusan angin dari arah laut membuat lokasi ini cocok untuk kegiatan olahraga paralayang. Bagi pengunjung yang lebih suka menikmati pemandangan dengan santai, puncak ini juga menjadi spot foto dan berkemah yang menarik.</p><h2>Akses</h2><p>Perjalanan menuju Puncak Gelendrung memerlukan pendakian ringan melalui jalur kampung di kawasan Gunung Rompang, disarankan menggunakan alas kaki yang nyaman untuk medan menanjak.</p>', 'published'),

  ('situs-gunung-rompang', 'Situs Gunung Rompang',
   '<p>Gunung Rompang tidak hanya dikenal karena panorama alamnya, tetapi juga menyimpan situs bersejarah yang menjadi bagian dari kisah masa lalu Desa Citarik. Situs ini kerap dikunjungi warga maupun peziarah dari luar desa.</p><h2>Daya Tarik</h2><p>Bagi pengunjung yang tertarik dengan wisata religi dan sejarah lokal, situs ini menawarkan suasana tenang di tengah kawasan perbukitan, jauh dari keramaian.</p><h2>Akses</h2><p>Situs ini berada satu kawasan dengan Puncak Gelendrung di Gunung Rompang, dapat dijangkau melalui jalur yang sama dari kampung terdekat.</p>', 'published'),

  ('kubang-hejo', 'Kubang Hejo',
   '<p>Kubang Hejo di Kampung Cibuntu dikenal sebagai sumber mata air sekaligus lokasi wisata religi bagi masyarakat Desa Citarik dan sekitarnya. Airnya yang jernih dipercaya memiliki nilai spiritual bagi sebagian warga.</p><h2>Daya Tarik</h2><p>Suasana rindang dan sumber air alami menjadikan Kubang Hejo tempat yang tenang untuk berziarah maupun sekadar beristirahat sejenak dari perjalanan menjelajahi Desa Citarik.</p><h2>Akses</h2><p>Lokasi ini berada di Kampung Cibuntu dan dapat dijangkau dengan kendaraan pribadi dari jalan utama desa.</p>', 'published'),

  ('benteng-Citarik', 'Benteng Peninggalan Belanda',
   '<p>Di kawasan pesisir Desa Citarik terdapat sisa benteng pertahanan dari masa kolonial Belanda. Dalam bahasa Belanda, bangunan pertahanan semacam ini disebut <em>loge</em>, yang artinya kantor atau markas pertahanan. Dari kata inilah nama Desa Citarik dipercaya berasal.</p><h2>Nilai Sejarah</h2><p>Menurut cerita masyarakat setempat, di sekitar benteng ini pernah terjadi pertempuran antara pasukan TNI bersama warga melawan penjajah pada masa perjuangan kemerdekaan. Keberadaan benteng ini menjadikannya salah satu penanda sejarah penting bagi identitas Desa Citarik.</p><h2>Kondisi Saat Ini</h2><p>Situs benteng ini masih ada hingga sekarang, meski penataannya sebagai objek wisata belum optimal. Ke depan, benteng ini berpotensi dikembangkan menjadi wisata sejarah yang melengkapi wisata bahari Desa Citarik.</p>', 'published')
ON CONFLICT(slug) DO UPDATE SET nama=excluded.nama, deskripsi_html=excluded.deskripsi_html, status=excluded.status, updated_at=datetime('now');

-- ── Berita: peluncuran situs resmi Desa Citarik oleh KKN-T IPB 2026 ──
INSERT OR IGNORE INTO berita (slug, judul, content_html, status, published_at) VALUES
  ('situs-resmi-desa-Citarik-diluncurkan-kknt-ipb-2026',
   'Situs Resmi Desa Citarik Resmi Diluncurkan, Hasil Kolaborasi dengan Mahasiswa KKN-T IPB 2026',
   '<p>Pemerintah Desa Citarik dengan bangga mengumumkan peluncuran situs web resmi Desa Citarik. Situs ini dibangun melalui kolaborasi antara Pemerintah Desa Citarik dan mahasiswa Kuliah Kerja Nyata Tematik (KKN-T) IPB University tahun 2026 yang bertugas di Desa Citarik, Kecamatan Simpenan, Kabupaten Sukabumi.</p><h2>Tujuan Pembuatan Situs</h2><p>Kehadiran situs ini diharapkan dapat meningkatkan transparansi informasi pemerintahan desa kepada masyarakat, sekaligus menjadi etalase digital untuk memperkenalkan potensi Desa Citarik, mulai dari wisata bahari dan alam, produk UMKM lokal, hingga profil dan data kependudukan desa, kepada khalayak yang lebih luas.</p><h2>Apa Saja yang Tersedia</h2><p>Melalui situs ini, pengunjung dapat menjelajahi profil lengkap desa, peta interaktif lokasi wisata dan fasilitas umum, direktori UMKM beserta kontak pelaku usahanya, berita dan informasi terkini seputar kegiatan desa, hingga struktur pemerintahan dan data kelembagaan masyarakat.</p><h2>Ucapan Terima Kasih</h2><p>Pemerintah Desa Citarik mengucapkan terima kasih kepada tim mahasiswa KKN-T IPB University 2026 atas kontribusi dan kerja samanya dalam mewujudkan situs ini. Semoga kehadiran situs ini dapat bermanfaat bagi masyarakat Desa Citarik, wisatawan, maupun pihak-pihak yang ingin mengenal Desa Citarik lebih jauh.</p>',
   'published', '2026-07-09T00:00:00.000Z');
